### ISSUE TITLE
building instructions

### ISSUE THREAD

**Issue by ghost** [Lmy0217/PyTorch-aarch64#1]
@Lmy0217 what are the building instructions?
how did you build

**Comment by Lmy0217** [comment]
`USE_CUDA=0 python setup.py install` in NanoPi.

**Comment by ghost** [comment]
that's it??
you didn't also set other values?
Also, did you build on a virtual qemu machine, or on the device itself?

**Comment by Lmy0217** [comment]
no other value, no virtual machine, on the device

**Comment by terryII** [comment]
could you upload the torchvision whl file which release is matching this torch version? thanks~
